# このサイト全体のタイトル
site_name: KINTOに新型クロスオーバーSUV「ヤリスクロス」が新登場！｜【KINTO】クルマのサブスク、トヨタから
og_title: og title

# meta description（og:description・twitter:descriptionでも使用）
description: KINTOでお得にヤリスクロスを手に入れよう！「買うよりお得、らしい」KINTOに2020年9月新型クロスオーバーSUV「ヤリスクロス」が新登場。

# meta keywords
keywords: [ヤリスクロス,ヤリス,トヨタ,キント,KINTO,サブスク,サブスクリプション,リース,フルサービス,愛車,コミコミ,保険,クレジットカード,ポイント,法人,頭金なし,借りる,安全装備,正規ディーラー,気軽,SUV]

orgin_link: ""
base_dir: /lp/yariscross/
# カノニカル・og:urlなどで使われる、このサイトのURL
# （複数ページあるサイトでは、全てに同じURLを入れないように）
url: /lp/yariscross/

# Facebook OGP・Twitter cardsで使われる画像 フルURLで指定すること
ogp_image_url: /ogp.png

# Facebookアプリのapp id（入れないとWarningが出る）
# facebook_app_id: 99999999999

# Twitter cardsの管理者として登録するアカウント（※任意）
# twitter_card_owner: '@'

# favicon
# favicon_url: /favicon.ico

# サイトをホーム画面に追加した際のアイコン画像
# webclipicon_url: http://example.com/webclipicon.png

# iOSにて、サイトをホーム画面に追加した際の、ステータスバーの挙動指定
# ios_status_bar: default