# このサイト全体のタイトル
site_name: site name
og_title: og title

# meta description（og:description・twitter:descriptionでも使用）
description: site description

# meta keywords
keywords: []

orgin_link: ""

# カノニカル・og:urlなどで使われる、このサイトのURL
# （複数ページあるサイトでは、全てに同じURLを入れないように）
url: 

# Facebook OGP・Twitter cardsで使われる画像 フルURLで指定すること
ogp_image_url: /ogp.png

# Facebookアプリのapp id（入れないとWarningが出る）
# facebook_app_id: 99999999999

# Twitter cardsの管理者として登録するアカウント（※任意）
# twitter_card_owner: '@'

# favicon
# favicon_url: /favicon.ico

# サイトをホーム画面に追加した際のアイコン画像
# webclipicon_url: http://example.com/webclipicon.png

# iOSにて、サイトをホーム画面に追加した際の、ステータスバーの挙動指定
# ios_status_bar: default